# Generated by Django 4.1.5 on 2023-01-23 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('corpo', models.TextField()),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado', models.DateField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RSC', 'Rascunho'), ('PUB', 'Publicado')], default='RSC', max_length=3)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publicado'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publicado'], name='blog_post_publica_176893_idx'),
        ),
    ]
